fix: Socket leak on error
logstash-plugins/logstash-input-websocket pull request #22
Opened 2019-12-21 01:30 UTC by stevenh

Fix sockets being leaked if we get any errors by calling agent.shutdown to close all active connections.

Also:
* Add retry configuration parameter.

Fixes #20

2019-12-21 01:40 UTC, stevenh commented
In the hope it will be helpful for others I had extreme difficulty getting to the stage I could run the rspec tests for this repo so here's some hints:
1.  ubuntu 18 LTS jruby in apt is broken don't us it, you need `9.2` or above otherwise you will just get an error trying to run `jruby -S bundle install`
```
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant SNAKEYAML_VERSION
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant ANY
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant UTF8
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant UTF16LE
/usr/lib/ruby/vendor_ruby/psych.rb:6: warning: already initialized constant UTF16BE
/usr/share/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: load error: psych -- java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.psych.PsychEmitter
           require at org/jruby/RubyKernel.java:956
           require at /usr/share/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
            <main> at /usr/share/jruby/lib/ruby/stdlib/yaml.rb:6
           require at org/jruby/RubyKernel.java:956
           require at /usr/share/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
            (root) at /usr/share/jruby/lib/ruby/stdlib/rubygems.rb:1
         load_yaml at /usr/share/jruby/lib/ruby/stdlib/rubygems.rb:701
         load_file at /usr/share/jruby/lib/ruby/stdlib/rubygems/config_file.rb:340
        initialize at /usr/share/jruby/lib/ruby/stdlib/rubygems/config_file.rb:202
  do_configuration at /usr/share/jruby/lib/ruby/stdlib/rubygems/gem_runner.rb:75
            <main> at /usr/share/jruby/lib/ruby/stdlib/rubygems/gem_runner.rb:40
              load at org/jruby/RubyKernel.java:974
            <main> at /usr/share/jruby/bin/gem:4
```
The latest version of jruby can be downloaded here:
[https://www.jruby.org/download](https://www.jruby.org/download)

2. This repo uses a logstash 5.6 which only supports java 8, if you use a later version you'll get the following error.
```
An error occurred while loading ./spec/inputs/websocket_spec.rb.
Failure/Error: require "logstash/devutils/rspec/spec_helper"

NameError:
  missing class name (`org.logstash.common.DeadLetterQueueFactory')
# ./spec/inputs/websocket_spec.rb:1:in `<main>'
```

In our case we not only got connections in `CLOSE_WAIT` but also in `ESTABLISHED` so many it ran the machine out of file handles, breaking everything.

2019-12-22 15:18 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +                 :retry => @interval) unless stop?
Is there any particular point with the special handling of EOFError given the subsequent catch-all rescue block?

2019-12-22 15:26 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +                     :retry => @interval) unless stop?
Why should 404s be treated differently that other status codes? Under which circumstances would one set `warn_404` to false?

2019-12-22 15:40 UTC, magnusbaeck requested changes
Apart from the inline comments that I'd like to talk about, the documentation in [master/docs/index.asciidoc](https://github.com/logstash-plugins/logstash-input-websocket/blob/master/docs/index.asciidoc) also needs to be updated. Previously the plugin documentation was generated from the comments in the code but nowadays it's maintained in separate files.

(I mistakenly added a couple of comments as single comments. They should've been part of the review.)

2019-12-22 15:40 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +    end
Nit: Equivalent and IMHO more idiomatic:

```ruby
else
  @interval = [@interval * 2, @retry_max].min
end
```

2019-12-22 15:40 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +  config :retry_reset, :validate => :number, :default => 20
Resetting the retry interval to the initial value after a certain number of iterations is not a pattern I have seen before. What's the rationale?

I don't think the description of the option is clear to people. Suggestion: "The number of errors that can occur before the retry interval is reset to `retry_interval`."

2019-12-22 19:06 UTC, stevenh commented on lib/logstash/inputs/websocket.rb
> +                 :retry => @interval) unless stop?
To avoid log spam when EOF is encountered its debug not warn. In our case that significantly reduced the amount of useless logging in normal operation.

2019-12-22 19:07 UTC, stevenh commented on lib/logstash/inputs/websocket.rb
> +                     :retry => @interval) unless stop?
We have it set to false as we expect 404 in normal operation i.e. the services are only there and listening when needed. This felt like a relatively special case hence the config option, defaulted to true to warn.

2019-12-22 19:09 UTC, stevenh commented on lib/logstash/inputs/websocket.rb
> +    end
Thanks, its been a loooong time since I did ruby ;-)

2019-12-22 19:12 UTC, stevenh commented on lib/logstash/inputs/websocket.rb
> +  config :retry_reset, :validate => :number, :default => 20
The backoff is there to ensure the service we're connecting to has chance to recover, however we don't want backoff to be permanent. Once we've successfully reconnected and processed some entries (`retry_rest`) the `interval` gets reset so we can quickly recover from a small interruptions.

2019-12-22 21:23 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +                 :retry => @interval) unless stop?
Oh dear, I totally missed the debug vs. warn difference despite comparing the two calls several times. Yes, it makes sense to not spam about closed connections.

2019-12-23 00:13 UTC, stevenh commented on lib/logstash/inputs/websocket.rb
> +                 :retry => @interval) unless stop?
Easy to miss, hopefully I've addressed all your other feedback too, but if I did miss anything just let me know.

2020-01-02 22:17 UTC, magnusbaeck requested changes
Sorry for the slow review. I found a few documentation nits, not terribly important but trivial to address, and I'm still not convinced by some of the proposed configuration options.

2020-01-02 22:17 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +  config :retry_reset, :validate => :number, :default => 20
I see. But why not just reset the backoff interval as soon as we've reconnected and processed a single message?

2020-01-02 22:17 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +                     :retry => @interval) unless stop?
In that case, how about instead adding an array option that lists which response codes should be ignored? The default would probably be empty but you could set it to `[404]`. That'd be more generic and, IMHO, easier to understand than a very specific option like `warn_404`.

2020-01-02 22:17 UTC, magnusbaeck commented on docs/index.asciidoc
> +| <<plugins-{type}s-{plugin}-warn_404>> |<<boolean,boolean>>|No
Maintain alphabetical order of options to make navigation easier?

2020-01-02 22:17 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +  config :warn_404, :validated => :boolean, :default => true
s/validated/validate/

2020-01-03 11:33 UTC, stevenh commented on lib/logstash/inputs/websocket.rb
> +  config :retry_reset, :validate => :number, :default => 20
If the service has an issue it may be able to connect and process a single message before failing again, so wanted a little more control over it than that.

Happy to have this default to 1, if you think that's better?

2020-01-03 11:40 UTC, stevenh commented on lib/logstash/inputs/websocket.rb
> +                     :retry => @interval) unless stop?
nice idea, will do.

2020-01-03 19:24 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +  config :retry_reset, :validate => :number, :default => 20
Okay. Let's keep it configurable but default to one.

2020-01-03 22:20 UTC, magnusbaeck requested changes
Sorry, just a few more things.

2020-01-03 22:20 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +  config :debug_status, :default => [404]
Add `:validate => :array`? (And change default value to empty array as per other discussion thread.)

2020-01-03 22:20 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +    if p.userinfo != ""
FWICT p.userinfo is nil if no credentials are provided so this should rather be:

    unless p.userinfo.nil?

As it stands we're adding "***:***" to the URL even if no credentials are provided which makes the log message confusing.

2020-01-10 09:34 UTC, stevenh commented
@magnusbaeck does this address all your concerns?

2020-01-10 09:45 UTC, magnusbaeck commented on lib/logstash/inputs/websocket.rb
> +  config :debug_status, :valdate => :array, :default => []
s/valdate/validate/

2020-01-10 09:46 UTC, magnusbaeck commented
Sorry, I've been very busy with other things this week. There's a small but significant typo in the last commit but otherwise we're good.

2020-01-10 09:51 UTC, stevenh commented on lib/logstash/inputs/websocket.rb
> +  config :debug_status, :valdate => :array, :default => []
Doh, fixed

2020-01-10 09:53 UTC, stevenh commented
No problem, totally appreciate that.

Typo fixed LMK if there's anything else as keen to get this closed out.

2020-01-12 20:35 UTC, magnusbaeck approved these changes

2020-01-12 20:57 UTC, merged

2020-01-12 21:25 UTC, magnusbaeck commented
Merged. Thanks for your patience! Unfortunately it turns out I lack permissions to publish the gem to rubygems.org, but I hope that'll get resolved during Monday.